[project]
name = "comfyui-lf"
description = "RGB histogram node, JSON nodes, LLM nodes and Logic Nodes."
version = "2.0.1"
license = {file = "LICENSE"}
dependencies = ["numpy", "openai==1.12.0", "Pillow", "torch", "requests"]

[project.urls]
Repository = "https://github.com/lucafoscili/comfyui-lf"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "lucafoscili"
DisplayName = "comfyui-lf"
Icon = ""
