name: Update Node Count

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  count-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Count Nodes
        run: |
          COUNT=$(grep -ro '# region' modules/nodes | wc -l)
          echo "{ \"nodes\": $COUNT }" > count.json

      - name: Create Pull Request with Node Count Update
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Update node count'
          title: 'Update node count'
          body: 'Automatically updates the node count.'
          branch: 'update-node-count-${{ github.run_id }}'
          labels: 'automated PR'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          add-paths: 'count.json'
