name: Update Node Count

on:
  push:
    branches:
      - master

# Grant write permissions to the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  count-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Count Nodes
        run: |
          COUNT=$(grep -ro '# region' modules/nodes | wc -l)
          echo "{ \"nodes\": $COUNT }" > count.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Updated node count'
          file_pattern: count.json
